export const userDb = [
    {
        id: 1,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 2,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 3,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 4,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 5,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 6,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 7,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 8,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 9,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 10,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 11,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 12,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
    {
        id: 13,
        userName: 'inku1',
        img: 'https://funzinnu.com/stream/cdn/dccon/%EB%A1%A4%EC%BD%94%ED%96%89%EB%B3%B5.gif',
        age: 35,
        status: 'active',
        email: 'necron7577@daum.net',
    },
];
